### ISSUE TITLE
[August ISO] System Clone goes to ISO Installer Dialog

### ISSUE THREAD

**Issue by 0pcom** [marotinhodimais/Maroto-iso#3]
I only noticed this yesterday, the system cloner on the August release goes to the installer dialog.

I called the system cloner with the keyboard shortcut: mod+i

I have noticed before at certain times that sometimes when the wrong options are chosen during installation or cloning, the dialog returns to a point on the installer dialog (the one you weren't intending to run), or vice versa.

On another, unrelated note, would you be interested in compiling Portergos for ARMv8?
I will donate all necessary hardware if you are interested in this.

Thanks for creating this wonderful OS! And for all the innovations such as the cloner. My favorite OS by far!

**Comment by Portergos** [comment]
Hi!
The "Clone" option was removed removed from the installer for some time now, you're probably using an old veriosn of it or using the "fork Portergos" from github which is old as well.

I probably won't work on ARMv8, in fact i don't have time to work on Portergos at least untill november/december. But you're welcome to fork it and make your own system.

Please keep in mind that Portergos is a free and volunteer OS made by one person, so don't expect too much of it.

I, for example, am thinking on removing things from portegos instead of adding more functionalities. Actually the system already does almost everything what i planned it to do (install Arch based system, Arch+Antergos+Portergos repositories without internet and with most of the packages i like to have).

Also be aware that i won't have time to work on it untill november/december, and then i'll probably update packages and remove more stuff to keep it simple.

**Comment by 0pcom** [comment]
That's all fine with me, I am only interested to support the 
development. I'm happy to see any direction you take with this OS
Eventually I hope to fork it.

thank you!

**Comment by 0pcom** [comment]
To clarify the issue; after the system has been installed from the ISO
mod+i should bring up the system clone dialog.

Here instead, the installation dialog is called:

![screenshot_2019-01-08_10-35-35](https://user-images.githubusercontent.com/36607567/50845050-9f648100-1331-11e9-9bfa-caf02c9c1d2d.png)

The installer dialog only works from the ISO, running through this dialog from an installed system fails.

I think when you removed the cloner dialog from the installer (menu option 0 when the ISO is booted) it altered the keyboard shortcut for the installed system (which iss supposed to call the cloner) to instead call the installer dialog again.

**Comment by Portergos** [comment]
Thanks for reporting, i'll check it when i have the time. I've been away from home for months now.
